name: Project Verification

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write

jobs:
  verify:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Hello World (PR)
      if: github.event_name == 'pull_request'
      id: hello
      run: |
        set -euo pipefail
        OUTPUT=$(bash scripts/hello.sh)
        echo "$OUTPUT"
        echo "output<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Comment hello output on PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ✅ CI Hello World

          ```
          ${{ steps.hello.outputs.output }}
          ```

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm install

    - name: Install all project dependencies
      run: npm run install:all

    - name: Run comprehensive verification
      run: npm run verify

    - name: Upload verification results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: verification-logs-${{ matrix.node-version }}
        path: |
          backend/dist/
          frontend/dist/
          backend/coverage/
          frontend/coverage/