name: Project Verification

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Hello World (PR)
      if: github.event_name == 'pull_request'
      run: bash scripts/hello.sh

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm install

    - name: Install all project dependencies
      run: npm run install:all

    - name: Run comprehensive verification
      run: npm run verify

    - name: Upload verification results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: verification-logs-${{ matrix.node-version }}
        path: |
          backend/dist/
          frontend/dist/
          backend/coverage/
          frontend/coverage/